2019-12-24 00:36:39,790 ERROR: Exception on / [GET] [in /home/sorvihead/git-projects/manage-data-course-project/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/sorvihead/git-projects/manage-data-course-project/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sorvihead/git-projects/manage-data-course-project/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sorvihead/git-projects/manage-data-course-project/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sorvihead/git-projects/manage-data-course-project/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/sorvihead/git-projects/manage-data-course-project/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sorvihead/git-projects/manage-data-course-project/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sorvihead/git-projects/manage-data-course-project/app/main/routes.py", line 47, in index
    show_followed=show_followed, pagination=pagination)
  File "/home/sorvihead/git-projects/manage-data-course-project/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/sorvihead/git-projects/manage-data-course-project/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/sorvihead/git-projects/manage-data-course-project/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/sorvihead/git-projects/manage-data-course-project/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/sorvihead/git-projects/manage-data-course-project/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sorvihead/git-projects/manage-data-course-project/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/sorvihead/git-projects/manage-data-course-project/app/templates/index.html", line 3, in top-level template code
    {% import "_macros.html" as macros %}
  File "/home/sorvihead/git-projects/manage-data-course-project/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/sorvihead/git-projects/manage-data-course-project/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/sorvihead/git-projects/manage-data-course-project/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/sorvihead/git-projects/manage-data-course-project/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/sorvihead/git-projects/manage-data-course-project/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/sorvihead/git-projects/manage-data-course-project/app/templates/base.html", line 77, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/sorvihead/git-projects/manage-data-course-project/app/templates/index.html", line 23, in block "app_content"
    {% include '_posts.html' %}
  File "/home/sorvihead/git-projects/manage-data-course-project/app/templates/_posts.html", line 29, in top-level template code
    <a href="{{ url_for('.post', id=post.id) }}">
  File "/home/sorvihead/git-projects/manage-data-course-project/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/sorvihead/git-projects/manage-data-course-project/venv/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/sorvihead/git-projects/manage-data-course-project/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/sorvihead/git-projects/manage-data-course-project/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/sorvihead/git-projects/manage-data-course-project/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.post' with values ['id']. Did you mean 'main.export_posts' instead?
2019-12-24 00:38:58,098 INFO: Microblog startup [in /home/sorvihead/git-projects/manage-data-course-project/app/__init__.py:89]
2019-12-24 00:45:51,367 INFO: Microblog startup [in /home/sorvihead/git-projects/manage-data-course-project/app/__init__.py:89]
